[build-system]
requires = ["setuptools>=42", "wheel", "pybind11>=2.6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["fin", "fin.core", "fin.bindings", "fin.tests"]

[tool.setuptools.package-data]
fin = ["_f5c/*.so", "_f5c/*.dylib", "_f5c/*.dll"]